// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: category.sql

package repository

import (
	"context"
	"database/sql"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO category (name, description)
VALUES (?, ?) RETURNING id
`

type CreateCategoryParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.Name, arg.Description)
	var id int64
	err := row.Scan(&id)
	return id, err
}
