// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"database/sql"
)

type Category struct {
	ID          int64
	Name        string
	Description sql.NullString
	CreatedAt   sql.NullTime
}

type Juror struct {
	ID        int64
	Slug      string
	Name      string
	CreatedAt sql.NullTime
}

type JurorCategory struct {
	ID         int64
	JurorID    int64
	CategoryID int64
	CreatedAt  sql.NullTime
}

type Model struct {
	ID          int64
	Name        string
	Author      string
	Description sql.NullString
	CreatedAt   sql.NullTime
	CategoryID  int64
}

type Vote struct {
	ID           int64
	QualityScore int64
	CreatedAt    sql.NullTime
	JurorID      sql.NullInt64
	ModelID      sql.NullInt64
}
