// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: model.sql

package repository

import (
	"context"
	"database/sql"
)

const createModel = `-- name: CreateModel :one
INSERT INTO model (name, author, description, category_id)
VALUES (?, ?, ?, ?) RETURNING id
`

type CreateModelParams struct {
	Name        string
	Author      string
	Description sql.NullString
	CategoryID  int64
}

func (q *Queries) CreateModel(ctx context.Context, arg CreateModelParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createModel,
		arg.Name,
		arg.Author,
		arg.Description,
		arg.CategoryID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
